apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tekton-role-binding
  namespace: default
  labels:
    app: tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton
subjects:
  - kind: ServiceAccount
    name: tekton
    namespace: default
