apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: cs-go-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
      - image: __IMAGE__